#!/bin/bash

echo "博文生成视频系统 - 开发环境启动"
echo "================================"
echo ""
echo "注意：请确保已安装并启动以下服务："
echo "  - PostgreSQL (端口 5432)"
echo "  - Redis (端口 6379)"
echo ""
echo "或者使用 Docker："
echo "  docker-compose up -d"
echo ""
echo "后端启动命令："
echo "  cd backend"
echo "  python -m venv venv"
echo "  source venv/bin/activate"
echo "  pip install -r requirements.txt"
echo "  cp .env.example .env"
echo "  # 编辑 .env 配置"
echo "  uvicorn app.main:app --reload --port 8000"
echo ""
echo "前端启动命令："
echo "  cd frontend"
echo "  npm install"
echo "  npm run dev"
