"""add scene_type field for rhythm rules

Revision ID: 4dcae3aa9cc8
Revises: 8269031e95f6
Create Date: 2026-04-21 11:33:16.307678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dcae3aa9cc8'
down_revision = '8269031e95f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column as nullable first (SQLite limitation)
    op.add_column('scenes', sa.Column('scene_type', sa.String(length=20), nullable=True))

    # Step 2: Set default value for existing rows
    op.execute("UPDATE scenes SET scene_type = 'explanation' WHERE scene_type IS NULL")

    # Step 3: Make column non-nullable (SQLite doesn't support ALTER COLUMN, so we skip this for SQLite)
    # For production with PostgreSQL/MySQL, you would add:
    # op.alter_column('scenes', 'scene_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'scene_type')
    # ### end Alembic commands ###
