"""add emphasis and timeline fields to scene

Revision ID: 8269031e95f6
Revises: b1c2d3e4f5a6
Create Date: 2026-04-21 11:18:26.639869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8269031e95f6'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assets_asset_type', table_name='assets')
    op.drop_index('ix_assets_job_id', table_name='assets')
    op.drop_index('ix_assets_project_id', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_job_logs_job_id', table_name='job_logs')
    op.drop_index('ix_job_logs_project_id', table_name='job_logs')
    op.drop_table('job_logs')
    op.drop_index('ix_ai_logs_job_id', table_name='ai_logs')
    op.drop_index('ix_ai_logs_operation', table_name='ai_logs')
    op.drop_index('ix_ai_logs_project_id', table_name='ai_logs')
    op.drop_table('ai_logs')
    op.drop_index('ix_scene_versions_project_id', table_name='scene_versions')
    op.drop_index('ix_scene_versions_scene_id', table_name='scene_versions')
    op.drop_table('scene_versions')
    op.add_column('scenes', sa.Column('emphasis_words', sa.JSON(), nullable=True))
    op.add_column('scenes', sa.Column('tts_metadata', sa.JSON(), nullable=True))
    op.add_column('scenes', sa.Column('timeline_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'timeline_data')
    op.drop_column('scenes', 'tts_metadata')
    op.drop_column('scenes', 'emphasis_words')
    op.create_table('scene_versions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scene_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('template_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('goal', sa.TEXT(), nullable=True),
    sa.Column('voiceover', sa.TEXT(), nullable=False),
    sa.Column('screen_text', sqlite.JSON(), nullable=False),
    sa.Column('duration_sec', sa.INTEGER(), nullable=False),
    sa.Column('pace', sa.VARCHAR(length=16), nullable=True),
    sa.Column('transition', sa.VARCHAR(length=16), nullable=True),
    sa.Column('visual_params', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scene_versions_scene_id', 'scene_versions', ['scene_id'], unique=False)
    op.create_index('ix_scene_versions_project_id', 'scene_versions', ['project_id'], unique=False)
    op.create_table('ai_logs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(), nullable=True),
    sa.Column('project_id', sa.VARCHAR(), nullable=True),
    sa.Column('operation', sa.VARCHAR(), nullable=False),
    sa.Column('model', sa.VARCHAR(), nullable=False),
    sa.Column('prompt', sa.TEXT(), nullable=False),
    sa.Column('response', sa.TEXT(), nullable=False),
    sa.Column('tokens_input', sa.INTEGER(), nullable=True),
    sa.Column('tokens_output', sa.INTEGER(), nullable=True),
    sa.Column('cost', sa.FLOAT(), nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_logs_project_id', 'ai_logs', ['project_id'], unique=False)
    op.create_index('ix_ai_logs_operation', 'ai_logs', ['operation'], unique=False)
    op.create_index('ix_ai_logs_job_id', 'ai_logs', ['job_id'], unique=False)
    op.create_table('job_logs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('stage', sa.VARCHAR(), nullable=False),
    sa.Column('level', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_logs_project_id', 'job_logs', ['project_id'], unique=False)
    op.create_index('ix_job_logs_job_id', 'job_logs', ['job_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('job_id', sa.VARCHAR(), nullable=False),
    sa.Column('asset_type', sa.VARCHAR(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(), nullable=False),
    sa.Column('file_url', sa.VARCHAR(), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('mime_type', sa.VARCHAR(), nullable=True),
    sa.Column('meta_data', sa.TEXT(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_project_id', 'assets', ['project_id'], unique=False)
    op.create_index('ix_assets_job_id', 'assets', ['job_id'], unique=False)
    op.create_index('ix_assets_asset_type', 'assets', ['asset_type'], unique=False)
    # ### end Alembic commands ###
